CREATE TABLE [Person].[CustomerEmail]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CustomerEmail_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	EmailAddress NVARCHAR(50) NOT NULL,
	CustomerId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CustomerEmail_CustomerId_Customer_Id FOREIGN KEY REFERENCES Person.Customer(Id)
)
