CREATE TABLE [Person].[Customer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Customer_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	[PersonId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Customer_PersonId_Person_Id FOREIGN KEY REFERENCES Person.Person(Id),
	[SalespersonId] UNIQUEIDENTIFIER CONSTRAINT FK_Customer_SalespersonId_Salesperson_Id FOREIGN KEY REFERENCES Person.Salesperson(Id),
	[CreatedDate] DATE NOT NULL DEFAULT CONVERT(DATE,GETUTCDATE())
)
