CREATE TABLE [Person].[CustomerAddress]
(
	Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_CustomerAddress_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	Street NVARCHAR(50) NOT NULL,
	City NVARCHAR(50) NOT NULL,
	StateProvince NVARCHAR(50) NOT NULL,
	PostalCode NVARCHAR(50) NOT NULL,
	Country NVARCHAR(50),
	CustomerId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_CustomerAddress_CustomerId_Customer_Id FOREIGN KEY REFERENCES Person.Customer(Id)
)
