--Exercise 9a - 9d

CREATE TABLE [Person].[Salesperson]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Salesperson_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(), 
    [PersonId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Salesperson_PersonId_Person_Id FOREIGN KEY REFERENCES Person.Person(Id), 
    [HiredDate] DATE NULL DEFAULT CONVERT (DATE, GETUTCDATE()), 
    [isActive] BIT NULL DEFAULT CAST(1 AS BIT), 
    [LoginId] UNIQUEIDENTIFIER NULL

)
