CREATE TABLE [dbo].[StateProvince]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_StateProvince_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	StateProvinceCode NCHAR(3) NOT NULL,
	CountryId UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_StateProvince_CountryId_Country_Id FOREIGN KEY REFERENCES dbo.Country(Id),
	[Name] NVARCHAR(50) NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETUTCDATE()

)
