CREATE TABLE [Inventory].[Color]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Color_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL ,
	[CreatedDate] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
