CREATE TABLE [Inventory].[Model]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Model_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL,
	[CreatedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[MakeId] UNIQUEIDENTIFIER CONSTRAINT FK_Model_MakeId_Make_Id FOREIGN KEY REFERENCES Inventory.Make(Id)
)
