CREATE TABLE [Inventory].[Vehicle]
(
	[Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_Vehicle_Id PRIMARY KEY CLUSTERED DEFAULT NEWID(),
	[MakeId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Vehicle_MakeId_Make_Id FOREIGN KEY REFERENCES Inventory.Make(Id),
	[ModelId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Vehicle_ModelId_Model_Id FOREIGN KEY REFERENCES Inventory.Model(Id),
	[Year] SMALLINT NOT NULL,
	[ColorId] UNIQUEIDENTIFIER NOT NULL CONSTRAINT FK_Vehicle_ColorId_Color_Id FOREIGN KEY REFERENCES Inventory.Color(Id),
	[Price] MONEY NOT NULL
)
